[build]
builder = "nixpacks"
buildCommand = "composer install && php artisan config:cache"

[deploy]
startCommand = "php artisan serve --host=0.0.0.0 --port=$PORT"
healthcheckPath = "/"
healthcheckTimeout = 100

[service]
name = "sudoku-app"